version: '3.8'

services:
  airflow:
    build: .
    container_name: nse-airflow
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
      - ./logs:/opt/airflow/logs
      - ./dbt_project/bse_analytics:/opt/airflow/dbt  # ðŸ‘ˆ Mount dbt project
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__CORE__PARALLELISM=2
      - AIRFLOW__CORE__DAG_CONCURRENCY=1
      - DBT_PROFILES_DIR=/opt/airflow/dbt/profiles  # ðŸ‘ˆ Tell dbt where config is
      
    command: >
      bash -c "airflow db init &&
               airflow users creatusername admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
               airflow standalone"
